-- MySQL Script generated by MySQL Workbench
-- Tue Jan 15 16:03:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smog_server
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smog_server
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smog_server` DEFAULT CHARACTER SET utf8 ;
USE `smog_server` ;

-- -----------------------------------------------------
-- Table `smog_server`.`smog_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smog_server`.`smog_history` ;

CREATE TABLE IF NOT EXISTS `smog_server`.`smog_history` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Pm10_value` DOUBLE NOT NULL,
  `Pm25_value` DOUBLE NOT NULL,
  `Sample_count` INT NOT NULL,
  `Period_from` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Period_to` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Execution_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
